const ABBREVIATIONS: Record<string, string> = {
  "Centering Breath": "C. Breath",
  "Mountain Pose": "Mt Pose",
  "Extended Mountain": "Ext Mt",
  "Standing Forward Fold": "Fwd Fold",
  "Half Lift": "Half Lift",
  "Chaturanga": "Ch'ranga",
  "Upward Dog": "Up Dog",
  "Downward Dog": "Dwndog",
  "Warrior I": "War I",
  "Warrior II": "War II",
  "Warrior III": "War III",
  "Low Lunge": "Lo Lunge",
  "Twisted Crescent": "Tw Cresc",
  "Figure 4 Balance": "Fig 4",
  "Dancing Shiva": "Dancer",
  "Standing Splits": "Std Split",
  "Skandasana": "Skanda",
  "Standing Hand-to-Big-Toe": "Hand-Toe",
  "Devotional Warrior": "Dev War",
  "Peaceful Warrior": "Peace War",
  "Extended Side Angle": "Side Ang",
  "Half Moon": "Half Moon",
  "Revolved Triangle": "Rev Tri",
  "Revolved Chair": "Rev Chair",
  "Forearm Plank": "FA Plank",
  "Constructive Rest": "Const Rest",
  "Supta Baddhakonasana": "Sup Bkona",
  "Gomukhasana": "Gomukha",
  "Janu Sirsasana": "Janu",
  "Seated Forward Fold": "Seat Fwd",
  "Supine Twist": "Sup Twist",
  "Happy Baby": "Hpy Baby",
  "Bound Angle": "Bnd Angle",
  "Wide-Angle Seated Fold": "Wide Fold",
  "Thread the Needle": "Thread",
  "Legs Up the Wall": "Legs Up",
  "Savasana": "Sav",
  "Child's Pose": "Child's",
};

export function abbreviatePose(poseName: string): string {
  return ABBREVIATIONS[poseName] ?? poseName;
}
